### ISSUE TITLE
How to increase antennas dbi

### ISSUE THREAD

**Issue by JHorlieca** [kent-williams/hotspot-utility#12]
How do I increase the antennas Dbi ?

**Comment by kent-williams** [comment]
This is not possible via the BLE interface.

**Comment by JHorlieca** [comment]
????????

**Comment by kent-williams** [comment]
@JHorlieca For starters, dBi (isotropic) gain, is only determined by the antenna geometry itself. This app is only meant to configure Wi-Fi and request useful confirmation and diagnostic information. Increasing the antenna dBi has nothing to do with this app.
