### ISSUE TITLE
Bulk registration of devices to wallets?

### ISSUE THREAD

**Issue by rsnodgrass** [kent-williams/hotspot-utility#16]
Any idea how you might be able to bulk register a bunch of hotspots to a wallet?  E.g. turn Bluetooth pairing on for 10 units, then use the app to assign them all to a Helium wallet address using the Pair mechanism?

Is this even a feature that could be added to this app?

**Comment by kent-williams** [comment]
This is possible in theory, but this particular app does not do onboarding for starters. It's possible hotspot manufactures may implement something like this in the future though for their own tools.

**Comment by kent-williams** [comment]
I'm going to close this as it will not become a feature of this app.
