### ISSUE TITLE
Ethernet = "disconnected"

### ISSUE THREAD

**Issue by GingerWorkman** [kent-williams/hotspot-utility#18]
Ethernet is displaying disconnect even though the hotspot is connected.  Verified by changes in block height and able to ping via "hotspotty" app. 

![IMG_2362](https://user-images.githubusercontent.com/98786481/151892883-c4e72842-4a3e-4f89-8c75-4835fac1b008.jpg)
![IMG_2360](https://user-images.githubusercontent.com/98786481/151893053-c771b494-9d30-4e85-92e5-2240179137eb.jpg)

**Comment by kent-williams** [comment]
Hi @GingerWorkman,

Thanks for reporting, but the ethernet status is read directly from the service on the hotspot that gathers this data. The app itself is not attempting to interpret anything itself. Sometimes the status of the Ethernet is not always the most up to date. I'm going to close this issue though as it is not related to the app itself.
