### ISSUE TITLE
NEEDING THE APP ON A LAPTOP COMPUTER

### ISSUE THREAD

**Issue by zlti-enterprize-llc** [kent-williams/hotspot-utility#19]
NEEDING, APP OR DOWNLOAD ON A LAPTOP...,BECAUSE THE POWER OF THE LAPTOP IS GREATER,& CAN BE SATSTABLE OF LONGER PERIODS ,THAN A PHONE....

**Comment by kent-williams** [comment]
There are no plans to develop a desktop version of this app.

**Comment by zlti-enterprize-llc** [comment]
WELL, HOW CAN YOU "BE A GREAT SYSTEM", WHEN THE SYSTEM CANT BE
UP-GRADED....???, MY HELIUM MINER-MENTED, IS NOT,DOING WHAT, IT
PROMISES,ME.......

**Comment by kent-williams** [comment]
This is not an official app from Helium.

**Comment by zlti-enterprize-llc** [comment]
SIR,CAN YOU,HELP,WITH FIXING THE SYSTEM,SO I CAN BE MAKING HELIUM......?????
