### ISSUE TITLE
This app is not available for any of your devices

### ISSUE THREAD

**Issue by sebastian-marinescu** [kent-williams/hotspot-utility#20]
Hello :) 

I found your app through this reddit-post:  https://www.reddit.com/r/HeliumNetwork/comments/18jw7jr/moved_the_location_of_my_miner_how_do_i_connect/

Unfortunately in the Play Store it says it isn't compatible with any of my devices. I'm using a Samsung S22+ with Android 14. 

Would it please be possible to allow newer devices/android-versions in the Play Store?

**Comment by kent-williams** [comment]
Thanks for letting me know, I'll look into this!

**Comment by RTSchriner** [comment]
@kent-williams I'm experiencing the same issue. My Android version is too new.

It's a great tool, I'd really love to continue using it.

Thanks!

**Comment by kent-williams** [comment]
I've had this on my list, but sounds like I need to bump it!

**Comment by Chelseajade1** [comment]
That would be great! I also really love this tool! If it’s possible, could you please also work on the “run diagnostic” feature. This feature no longer functions on Apple or android.

**Comment by kent-williams** [comment]
@Chelseajade1 The problem with the diagnostics is that every manufacturer ended up implementing their own interface for this. Which hotspot makes are you having trouble with?

**Comment by Chelseajade1** [comment]
Syncrobit, if possible. However just having the ability to easily connect devices to WiFi again is great! Thank you Kent!

**Comment by kent-williams** [comment]
Apologies all, but the codebase is so out of date at this point that it would essentially take a rewrite. Sadly I don't have the time to undertake this.
